### ISSUE TITLE
Zpětná vazba No. 2

### ISSUE THREAD

**Issue by JanaNovotna** [Justisedli/PROJEKT-Vizitka#1]
Ahoj! 

tak pokračujeme :) 

Pěkná práce. Mám jen pár tipů (dva tipy) na to, jak mít přhlednější CSS soubor :) 
- Co  můžeš napsat do vícenásobného selektoru, napiš to tam. 
Tady se můžeme podívat na Facebook a twitter - hodně věcí mají společných: šířku, padding, margin, zaoblení rohů... všechny, co mají společné můžeš napsat dohromady a pak zvlášť jen to, co se líší, v tomto případě barvy. Na začátku to bude asi složitější, ale časem to bude super, protože nebudeš mít kilometr dlouhý CSS :) 
- zkrácené zápisy vlastností - např. padding a margin 
To co píšeš jako padding-top: 5px, padding-right: 10px, padding-bottom: 5px a padding-left: 15px (nebo margin), lze napsat zkráceně padding: 5px 10px 5px 15px; (čísla si cucám z prstu). Za a) to ušetří spoustu psaní (kodéři i programátoři jsou lenoši) a za b) nakonec to bude i přehlednější. Pokud nějakou hodnotu nenestavuješ, napiš tam místo čísla "auto".

Snad jsem to naspala pochopitelně, kdyby ne, tak se ozvi :) 

Janča

**Comment by Justisedli** [comment]
Ahoj, moc děkuji za zpětnou vazbu a super tipy pro tvorbu v css. 
Justina
